debian/tmp/usr/lib/indicator-applet/indicator-applet
debian/tmp/usr/share/dbus-1/services/org.consort.panel.applet.IndicatorAppletFactory.service
debian/tmp/usr/share/consort-panel/1.0/applets/org.ayatana.panel.IndicatorApplet.panel-applet
debian/tmp/usr/share/icons
debian/tmp/usr/share/locale
debian/source_indicator-applet.py usr/share/apport/package-hooks
debian/indicator-applet-crashdb.conf /etc/apport/crashdb.conf.d/
